extends: standard-with-typescript

parser: '@typescript-eslint/parser'

parserOptions:
  project: ./tsconfig.json

overrides:
  - files: '**/*.test.ts'
    plugins:
      - jest
    extends: plugin:jest/all
