extends: standard-with-typescript

parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json

rules:
  # Disable rules that conflict with prettier.
  '@typescript-eslint/semi': 0
  semi: 0
  comma-dangle: 0
  object-curly-spacing: 0
  '@typescript-eslint/space-before-function-paren': 0
  space-before-function-paren: 0
  '@typescript-eslint/member-delimiter-style': 0
  '@typescript-eslint/indent': 0
  'no-void': 0

  '@typescript-eslint/explicit-function-return-type': 0
  'standard/no-callback-literal': 0
  '@typescript-eslint/no-shadow': 2

  # Override the default configuration of the strict-boolean-expressions rule to
  # allow safe boolean conversion of non-nullable strings, numbers and objects.
  '@typescript-eslint/strict-boolean-expressions':
    - error
    - allowString: true
      allowNumber: true
      allowNullableObject: true

overrides:
  - files: '**/*.test.ts'
    plugins:
      - jest
    extends: plugin:jest/all
