# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml
service: api-gateway

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

custom:
  serverless-offline:
    resourceRoutes: true

functions:
  hello:
    name: hello-${opt.stage}
    handler: src/handler.hello
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /hello
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(models/HelloRequest.v1.yaml)}
