openapi: 3.0.0
info:
  title: gateway
  version: '1.0'
servers:
  - url: 'https://unfifsuekk.execute-api.us-west-2.amazonaws.com/prod'
paths:
  /contacts:
    get:
      operationId: get-contacts
      summary: List Contacts
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: ../models/generated/schema.json#/definitions/Contact
              examples: {}
  /accounts:
    get:
      summary: List Accounts
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: ../models/generated/schema.json#/definitions/Account
              examples: {}
      operationId: get-accounts
    post:
      summary: Create Account
      operationId: post-accounts
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties: {}
      parameters:
        - schema:
            type: string
            default: application/vnd.api+json
          in: header
          name: Accept
          required: true
        - schema:
            type: string
            default: application/vnd.api+json
          in: header
          name: Content-Type
          required: true
  '/accounts/{id}/relationships/contacts':
    parameters:
      - schema:
          type: string
          example: i
        name: id
        in: path
        required: true
    post:
      summary: Add Account Contact
      operationId: post-accounts-id-relationships-contacts
      responses:
        '200':
          description: OK
    delete:
      summary: Remove Account Contact
      operationId: delete-accounts-id-relationships-contacts
      responses:
        '200':
          description: OK
