openapi: 3.0.0
info:
  title: gateway
  version: '1.0'
servers:
  - url: 'https://unfifsuekk.execute-api.us-west-2.amazonaws.com/prod'
paths:
  /contacts:
    get:
      operationId: list-contacts
      summary: List Contacts
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: ../models/generated/Contact.json
              examples: {}
  /accounts:
    get:
      summary: List Accounts
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: ../models/generated/Account.json
              examples: {}
      operationId: get-accounts
