openapi: 3.0.0
info:
  title: api
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    CustomerAccount:
      title: CustomerAccount
      allOf:
        - type: object
          properties:
            uuid:
              type: string
              format: uuid
              description: '[source](https://github.com/crucible-risk/servers_common/blob/f1028ae/common/models/models_account.py#L25)'
              example: 123e4567-e89b-12d3-a456-426614174000
          required:
            - uuid
        - $ref: '#/components/schemas/CustomerAttributeFields'
        - $ref: '#/components/schemas/TimestampFields'
      x-examples: {}
      x-tags:
        - resource
    MailingAddress:
      title: MailingAddress
      type: object
      description: A mailing address.
      properties:
        line1:
          type: string
          description: |-
            The first line of the address. Typically the street address or PO Box number.

            [source](https://github.com/crucible-risk/servers_common/blob/cb38571/common/models/models_address.py#L40)
          example: 1160 Battery St.
        line2:
          type: string
          description: |-
            The second line of the address. Typically the number of the apartment, suite, or unit.

            [source](https://github.com/crucible-risk/servers_common/blob/cb38571/common/models/models_address.py#L41)
          example: Ste 350
        city:
          type: string
          description: |-
            The name of the city, district, village, or town.

            [source](https://github.com/crucible-risk/servers_common/blob/cb38571/common/models/models_address.py#L42)
          example: San Francisco
        state_code:
          type: string
          description: |-
            The region of the address, such as the province, state, or district.

            [source](https://github.com/crucible-risk/servers_common/blob/cb38571/common/models/models_address.py#L44)
          example: CA
        country_code:
          type: string
          description: |-
            Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).

            [source](https://github.com/crucible-risk/servers_common/blob/cb38571/common/models/models_address.py#L43)
          example: US
        postal_code:
          type: string
          description: |-
            The zip or postal code of the address.

            [source](https://github.com/crucible-risk/servers_common/blob/cb38571/common/models/models_address.py#L45)
          example: '94111'
        formatted:
          type: string
          description: A formatted version of the address.
          example: |-
            1160 Battery St.
            Ste 350
            San Francisco CA 94111
            United States
      x-tags:
        - model
    Currency:
      title: Currency
      type: object
      properties:
        code:
          type: string
          description: 'Three-letter [ISO currency code]( ISO currency code), in lowercase'
          example: USD
        amount:
          type: integer
          description: 'Amount in the smallest possible denomination of the currency. E.g. for USD, amount=100 means 100 cents (1 dollar.)'
          example: 1000000
        formatted:
          readOnly: true
          type: string
          example: '$10,000'
      required:
        - code
        - amount
        - formatted
    Policy:
      title: Policy
      allOf:
        - type: object
          properties:
            cpn:
              type: string
              example: C-4LPA-123456-CYBER-2020-A
            limit:
              $ref: '#/components/schemas/Currency'
            retention:
              $ref: '#/components/schemas/Currency'
            premium:
              $ref: '#/components/schemas/Currency'
            market:
              $ref: '#/components/schemas/PolicyMarket'
            effective_date:
              type: string
              format: date-time
            end_date:
              type: string
              format: date-time
            status:
              $ref: '#/components/schemas/PolicyStatus'
            coverages:
              type: array
              uniqueItems: false
              items:
                $ref: '#/components/schemas/PolicyCoverage'
          required:
            - cpn
            - limit
            - retention
            - premium
            - market
            - effective_date
            - end_date
            - status
        - $ref: '#/components/schemas/CustomerAttributeFields'
      description: ''
      x-tags:
        - resource
    User:
      title: User
      type: object
      properties:
        id:
          type: string
    PolicyMarket:
      title: PolicyMarket
      type: object
      properties:
        name:
          type: string
          example: SURPLUS
        label:
          type: string
          example: Surplus
      required:
        - name
        - label
    PolicyStatus:
      title: PolicyStatus
      discriminator:
        propertyName: type
      type: object
      properties:
        name:
          type: string
          example: EFFECTIVE
        label:
          type: string
          example: Effective
    Industry:
      title: Industry
      type: object
      properties:
        id:
          type: integer
          example: 778
        label:
          type: string
          example: Insurance - Multi-line Insurance / Carrier
      required:
        - id
        - label
      x-tags:
        - resource
    CustomerAttributeFields:
      title: CustomerAttributeFields
      type: object
      properties:
        mailing_address:
          $ref: '#/components/schemas/MailingAddress'
        industry_name:
          type: string
          example: Insurance - Multi-line Insurance / Carrier
        employee_count:
          type: string
          example: 1-25
        annual_revenue:
          $ref: '#/components/schemas/Currency'
        name:
          type: string
      required:
        - mailing_address
        - industry_name
        - employee_count
        - annual_revenue
        - name
      x-tags:
        - partial
    PolicyCoverage:
      title: PolicyCoverage
      type: object
      description: ''
      x-tags:
        - join
      properties:
        type:
          type: string
          example: breach_response
        label:
          type: string
          example: Breach Response
        limit:
          $ref: '#/components/schemas/Currency'
        retention:
          $ref: '#/components/schemas/Currency'
      required:
        - type
        - label
    PolicyDocument:
      title: PolicyDocument
      type: object
      properties:
        type:
          type: string
          example: CYBER_RISK_ASSESSMENT
          description: ''
        file:
          $ref: '#/components/schemas/File'
      x-examples: {}
      description: ''
      x-tags:
        - join
    File:
      title: File
      x-examples: {}
      allOf:
        - type: object
          properties:
            type:
              type: string
              description: '[RFC 6838](https://tools.ietf.org/html/rfc6838) media type.'
              example: application/pdf
            url:
              type: string
              description: Signed download url.
              example: 'https://coalition-example.s3.amazonaws.com/123e4567-e89b-12d3-a456-426614174000/CYBER_RISK_ASSESSMENT.pdf?AWSAccessKeyId=XXXXXXXXXXXXXXXXXXXX&Expires=1602087968'
            name:
              type: string
              description: File name encluding extension.
              example: CYBER_RISK_ASSESSMENT.pdf
        - $ref: '#/components/schemas/TimestampFields'
      x-tags:
        - resource
    TimestampFields:
      title: TimestampFields
      type: object
      x-examples: {}
      properties:
        created_at:
          type: string
          format: date-time
          description: Date and time resource was first created.
        updated_at:
          type: string
          format: date-time
          description: Date and time resource was last updated.
      required:
        - created_at
        - updated_at
